name: Scheduled Deploy to GitHub Pages

on:
  schedule:
    - cron: '20 20 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout schedule branch
        uses: actions/checkout@v3
        with:
          ref: schedule
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to main and merge
        run: |
          git fetch origin main
          git checkout main || git checkout -b main origin/main
          git merge origin/schedule -m "Scheduled update from schedule branch"
          git push origin main